backend:
  name: github
  repo: SovereignCloudStack/sovereigncloudstack.org
  branch: main
  auth_scope: repo
  base_url: https://www.sovereigncloudstack.org
  auth_endpoint: /api/auth
media_folder: public/img
public_folder: img
locales: [en, de]
default_locale: en
collections:
  - name: "pages"
    label: "Pages"
    i18n:
      structure: single_file
      locales: [en, de]
    files:
      - label: "Index"
        name: "index"
        file: "content/index.md"
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - label: Meta
            name: meta
            widget: object
            i18n: true
            fields:
              - { label: Description, name: description, widget: text, i18n: true }
              - { label: OG Description, name: og_description, widget: text, i18n: true }
              - { label: OG URL, name: og_url, widget: string, i18n: true }
              - { label: OG Site Name, name: og_site_name, widget: string, i18n: true }
              - { label: OG Title, name: og_title, widget: string, i18n: true }
              - { label: OG Type, name: og_type, widget: string, i18n: true }
              - { label: OG Image, name: og_image, widget: string, i18n: true }
          - label: Sections
            name: sections
            widget: list
            i18n: true
            types:
              - label: Hero Section
                name: hero
                widget: object
                fields:
                  - { label: Headline 1, name: headline1, widget: string, i18n: true }
                  - { label: Headline 2, name: headline2, widget: string, i18n: true }
                  - label: Text 1
                    name: text1
                    widget: object
                    i18n: true
                    fields:
                      - { label: Title, name: title, widget: string, i18n: true }
                      - { label: Button, name: button, widget: object, i18n: true, fields: [{ label: Label, name: label, widget: string, i18n: true }, { label: Href, name: href, widget: string, i18n: true }] }
                  - label: News
                    name: news
                    widget: object
                    i18n: true
                    fields:
                      - { label: Title, name: title, widget: string, i18n: true }
                      - { label: Date, name: date, widget: string, i18n: true }
                      - { label: Body, name: body, widget: text, i18n: true }
                      - { label: Link URL, name: linkUrl, widget: string, i18n: true }
                      - { label: Link Text, name: linkText, widget: string, i18n: true }
              - label: Second Section
                name: second
                widget: object
                fields:
                  - { label: Headline, name: headline1, widget: string, i18n: true }
                  - label: Boxes
                    name: boxes
                    widget: list
                    i18n: true
                    fields:
                      - { label: Title, name: title, widget: string, i18n: true }
                      - { label: Text, name: text, widget: text, i18n: true }
                      - { label: Button, name: button, widget: object, i18n: true, fields: [{ label: Label, name: label, widget: string, i18n: true }, { label: Href, name: href, widget: string, i18n: true }] }
              - label: Third Section
                name: third
                widget: object
                fields:
                  - { label: Headline, name: headline1, widget: string, i18n: true }
                  - { label: Text, name: text, widget: text, i18n: true }
              - label: Fourth Section
                name: fourth
                widget: object
                fields:
                  - { label: Headline 1, name: headline1, widget: string, i18n: true }
                  - { label: Headline 2, name: headline2, widget: string, i18n: true }
                  - { label: Text, name: text, widget: text, i18n: true }
                  - { label: Link URL, name: linkUrl, widget: string, i18n: true }
                  - { label: Link Text, name: linkText, widget: string, i18n: true }
                  - label: Personas
                    name: personas
                    widget: list
                    i18n: true
                    fields:
                      - { label: Title, name: title, widget: string, i18n: true }
                      - { label: Text, name: text, widget: text, i18n: true }
